db.driver=com.mysql.cj.jdbc.Driver
db.jdbcUrl=jdbc:mysql://localhost:3308/db_class?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
db.username=student
db.password=3057
# 최대 풀 사이즈
hikari.maximumPoolSize=5
hikari.connectionTimeoutMs=30000
