/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2025-11-22 12:47:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("  <title>소리집 sorizip – 소리를 담은 집, 중고 악기 장터</title>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n");
      out.write("  <style>\n");
      out.write("    *{box-sizing:border-box}\n");
      out.write("    body{margin:0;font-family:system-ui,Apple SD Gothic Neo,Segoe UI,Roboto}\n");
      out.write("    .nav{display:flex;gap:16px;align-items:center;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #eee;background:#fff;position:sticky;top:0}\n");
      out.write("    .brand{font-weight:700}.brand .sub{font-weight:400;color:#9a6a00}\n");
      out.write("    .nav nav a{margin:0 8px;color:#444;text-decoration:none}\n");
      out.write("    .btn{padding:8px 14px;border:1px solid #ff8a00;border-radius:10px;background:#fff;text-decoration:none}\n");
      out.write("    .btn.primary{background:#ff8a00;color:#fff;border-color:#ff8a00}\n");
      out.write("    .btn.ghost{border-color:#ccc;color:#333}\n");
      out.write("    .hero{height:360px;background:url('assets/img/hero.jpg') center/cover no-repeat;display:flex;align-items:center;justify-content:center;position:relative}\n");
      out.write("    .hero::after{content:\"\";position:absolute;inset:0;background:rgba(255,255,255,.55)}\n");
      out.write("    .hero-text{position:relative;text-align:center;padding:0 12px}\n");
      out.write("    .hero-text h1{margin:0 0 8px}\n");
      out.write("    .section{padding:36px 18px;max-width:980px;margin:0 auto}\n");
      out.write("    .grid-3{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}\n");
      out.write("    .card{border:1px solid #eee;border-radius:14px;padding:14px;background:#fff;box-shadow:0 2px 10px rgba(0,0,0,.03);text-decoration:none;color:inherit}\n");
      out.write("    .card h3{margin:0 0 6px}\n");
      out.write("    .card.product{padding:0;overflow:hidden;display:block}\n");
      out.write("    .card .thumb{height:160px;background:#f5f5f5 center/cover no-repeat}\n");
      out.write("    .card .meta{padding:12px}\n");
      out.write("    .row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}\n");
      out.write("    .muted{color:#888;font-size:.9rem}\n");
      out.write("    .price{font-weight:700}\n");
      out.write("    .tag{padding:2px 8px;border:1px solid #ddd;border-radius:999px;font-size:.8rem}\n");
      out.write("    .chips{display:flex;flex-wrap:wrap;gap:8px}\n");
      out.write("    .chip{padding:8px 10px;background:#fff;border:1px solid #eee;border-radius:999px}\n");
      out.write("    .cta{text-align:center;background:#fff7ee;border:1px solid #ffe1c2;border-radius:16px}\n");
      out.write("    .footer{padding:18px;color:#777;text-align:center;border-top:1px solid #eee}\n");
      out.write("    @media (max-width:900px){.grid-3{grid-template-columns:1fr 1fr}}\n");
      out.write("    @media (max-width:560px){.grid-3{grid-template-columns:1fr}}\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<header class=\"nav\">\n");
      out.write("  <div class=\"brand\">소리집 <span class=\"sub\">sorizip</span></div>\n");
      out.write("  <nav>\n");
      out.write("    <a href=\"#features\">서비스 소개</a>\n");
      out.write("    <a href=\"#categories\">카테고리</a>\n");
      out.write("    <a href=\"#market\">추천 매물</a>\n");
      out.write("    <a href=\"#cta\">시작하기</a>\n");
      out.write("  </nav>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<section class=\"hero\">\n");
      out.write("  <div class=\"hero-text\">\n");
      out.write("    <h1>소리를 담은 집, <span>sorizip</span></h1>\n");
      out.write("    <p>기타, 피아노, 드럼부터 관악기까지. 믿고 거래하는 중고 악기 장터.</p>\n");
      out.write("    <div class=\"cta-row\" style=\"display:flex;gap:10px;justify-content:center;margin-top:10px\">\n");
      out.write("      <a class=\"btn primary\" href=\"#market\">추천 매물 보기</a>\n");
      out.write("      <a class=\"btn ghost\" href=\"#features\">서비스 소개</a>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<section id=\"features\" class=\"section\">\n");
      out.write("  <h2>왜 소리집인가</h2>\n");
      out.write("  <div class=\"grid-3\">\n");
      out.write("    <a class=\"card\" href=\"#\">\n");
      out.write("      <h3>악기 특화 검색</h3>\n");
      out.write("      <p>브랜드, 모델, 상태, 도시, 가격으로 정밀 필터를 제공합니다.</p>\n");
      out.write("    </a>\n");
      out.write("    <a class=\"card\" href=\"#\">\n");
      out.write("      <h3>안심 거래 가이드</h3>\n");
      out.write("      <p>대면 체크리스트와 직거래 안전 수칙으로 분쟁을 줄입니다.</p>\n");
      out.write("    </a>\n");
      out.write("    <a class=\"card\" href=\"#\">\n");
      out.write("      <h3>투명한 매물 정보</h3>\n");
      out.write("      <p>실사진, 상태표기, 점검 내역을 한눈에 확인할 수 있습니다.</p>\n");
      out.write("    </a>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<section id=\"categories\" class=\"section\">\n");
      out.write("  <h2>주요 카테고리</h2>\n");
      out.write("  <div class=\"chips\">\n");
      out.write("    <span class=\"chip\">어쿠스틱 기타</span>\n");
      out.write("    <span class=\"chip\">일렉 기타</span>\n");
      out.write("    <span class=\"chip\">베이스</span>\n");
      out.write("    <span class=\"chip\">피아노</span>\n");
      out.write("    <span class=\"chip\">신디사이저</span>\n");
      out.write("    <span class=\"chip\">관악기</span>\n");
      out.write("    <span class=\"chip\">드럼</span>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<section id=\"market\" class=\"section\">\n");
      out.write("  <h2>추천 매물</h2>\n");
      out.write("  <div class=\"grid-3\">\n");
      out.write("    <a class=\"card product\" href=\"#\">\n");
      out.write("      <div class=\"thumb\" style=\"background-image:url('assets/img/u1.jpg')\"></div>\n");
      out.write("      <div class=\"meta\">\n");
      out.write("        <h3>야마하 업라이트 U1</h3>\n");
      out.write("        <p class=\"muted\">Yamaha</p>\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <span class=\"price\">1,800,000원</span>\n");
      out.write("          <span class=\"tag\">good</span>\n");
      out.write("          <span class=\"muted\">서울</span>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </a>\n");
      out.write("\n");
      out.write("    <a class=\"card product\" href=\"#\">\n");
      out.write("      <div class=\"thumb\" style=\"background-image:url('assets/img/strat.jpg')\"></div>\n");
      out.write("      <div class=\"meta\">\n");
      out.write("        <h3>펜더 스트라토캐스터</h3>\n");
      out.write("        <p class=\"muted\">Fender</p>\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <span class=\"price\">950,000원</span>\n");
      out.write("          <span class=\"tag\">like-new</span>\n");
      out.write("          <span class=\"muted\">부산</span>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </a>\n");
      out.write("\n");
      out.write("    <a class=\"card product\" href=\"#\">\n");
      out.write("      <div class=\"thumb\" style=\"background-image:url('assets/img/fp30x.jpg')\"></div>\n");
      out.write("      <div class=\"meta\">\n");
      out.write("        <h3>롤랜드 디지털피아노 FP-30X</h3>\n");
      out.write("        <p class=\"muted\">Roland</p>\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <span class=\"price\">680,000원</span>\n");
      out.write("          <span class=\"tag\">good</span>\n");
      out.write("          <span class=\"muted\">대구</span>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </a>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<section id=\"cta\" class=\"section cta\">\n");
      out.write("  <h2>지금 시작하세요</h2>\n");
      out.write("  <p>회원가입 없이도 구경 가능. 로그인 기능은 추후 연동 예정입니다.</p>\n");
      out.write("  <a class=\"btn primary\" href=\"#market\">매물 보러가기</a>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer class=\"footer\">\n");
      out.write("  <div>© ");
      out.print( java.time.Year.now() );
      out.write(" sorizip</div>\n");
      out.write("  <div>문의: support@sorizip.example</div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
