/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2025-11-24 13:50:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

  // 로그인 상태 확인
  Integer userId = (Integer) session.getAttribute("userId");
  String userUId = (String) session.getAttribute("userUId");
  boolean isLoggedIn = (userId != null && userUId != null);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("  <title>소리집 sorizip – 소리를 담은 집, 중고 악기 장터</title>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/index.css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<header class=\"nav\">\n");
      out.write("  <a href=\"index.jsp\" class=\"brand\">소리집 <span class=\"sub\">sorizip</span></a>\n");
      out.write("  <nav>\n");
      out.write("    <a href=\"#features\">서비스 소개</a>\n");
      out.write("    <a href=\"#market\">추천 매물</a>\n");
      out.write("    <a href=\"#cta\">시작하기</a>\n");
      out.write("    ");
 if (isLoggedIn) { 
      out.write("\n");
      out.write("      <span style=\"color: #666; margin-right: 10px;\">");
      out.print( userUId );
      out.write("님</span>\n");
      out.write("      <a href=\"new.jsp\" style=\"color: #FF6B35; font-weight: 600;\">+ 매물 등록</a>\n");
      out.write("      <a href=\"#\" onclick=\"return confirmLogout();\" style=\"color: #999;\">로그아웃</a>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("      <a href=\"login.jsp\" style=\"color: #FF6B35; font-weight: 600;\">로그인</a>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </nav>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  function confirmLogout() {\n");
      out.write("    if (confirm('로그아웃 하시겠습니까?')) {\n");
      out.write("      window.location.href = 'logout';\n");
      out.write("      return true;\n");
      out.write("    }\n");
      out.write("    return false;\n");
      out.write("  }\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<section class=\"hero\">\n");
      out.write("  <div class=\"hero-text\">\n");
      out.write("    <h1>소리를 담은 집, <span>sorizip</span></h1>\n");
      out.write("    <p>기타, 피아노, 드럼부터 관악기까지. 믿고 거래하는 중고 악기 장터.</p>\n");
      out.write("\n");
      out.write("    <!-- 검색바 -->\n");
      out.write("    <form id=\"searchForm\" class=\"search-bar\" method=\"get\" action=\"search.jsp\">\n");
      out.write("      <input\n");
      out.write("        type=\"text\"\n");
      out.write("        name=\"q\"\n");
      out.write("        id=\"searchInput\"\n");
      out.write("        class=\"search-input\"\n");
      out.write("        placeholder=\"악기 이름, 브랜드, 도시로 검색해보세요\"\n");
      out.write("      />\n");
      out.write("      <button type=\"submit\" class=\"btn primary\">검색</button>\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <div class=\"cta-row\">\n");
      out.write("      <a class=\"btn primary\" href=\"search.jsp\">매물 보러가기</a>\n");
      out.write("      <a class=\"btn ghost\" href=\"#market\">추천 매물 보기</a>\n");
      out.write("      <a class=\"btn ghost\" href=\"#features\">서비스 소개</a>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<section id=\"categories\" class=\"section\">\n");
      out.write("  <h2>주요 카테고리</h2>\n");
      out.write("  <div class=\"chips\">\n");
      out.write("    <a class=\"chip\" href=\"search.jsp?category=어쿠스틱 기타\">어쿠스틱 기타</a>\n");
      out.write("    <a class=\"chip\" href=\"search.jsp?category=일렉 기타\">일렉 기타</a>\n");
      out.write("    <a class=\"chip\" href=\"search.jsp?category=베이스\">베이스</a>\n");
      out.write("    <a class=\"chip\" href=\"search.jsp?category=피아노\">피아노</a>\n");
      out.write("    <a class=\"chip\" href=\"search.jsp?category=신디사이저\">신디사이저</a>\n");
      out.write("    <a class=\"chip\" href=\"search.jsp?category=관악기\">관악기</a>\n");
      out.write("    <a class=\"chip\" href=\"search.jsp?category=드럼\">드럼</a>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<section id=\"market\" class=\"section\">\n");
      out.write("  <h2>추천 매물</h2>\n");
      out.write("  <div class=\"grid-3\">\n");
      out.write("    <a class=\"card product\" href=\"#\"\n");
      out.write("       data-title=\"야마하 업라이트 U1\"\n");
      out.write("       data-brand=\"Yamaha\"\n");
      out.write("       data-city=\"서울\">\n");
      out.write("      <div class=\"thumb\"></div>\n");
      out.write("      <div class=\"meta\">\n");
      out.write("        <h3>야마하 업라이트 U1</h3>\n");
      out.write("        <p class=\"muted\">Yamaha</p>\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <span class=\"price\">1,800,000원</span>\n");
      out.write("          <span class=\"tag\">good</span>\n");
      out.write("          <span class=\"muted\">서울</span>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </a>\n");
      out.write("\n");
      out.write("    <a class=\"card product\" href=\"#\"\n");
      out.write("       data-title=\"펜더 스트라토캐스터\"\n");
      out.write("       data-brand=\"Fender\"\n");
      out.write("       data-city=\"부산\">\n");
      out.write("      <div class=\"thumb\"></div>\n");
      out.write("      <div class=\"meta\">\n");
      out.write("        <h3>펜더 스트라토캐스터</h3>\n");
      out.write("        <p class=\"muted\">Fender</p>\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <span class=\"price\">950,000원</span>\n");
      out.write("          <span class=\"tag\">like-new</span>\n");
      out.write("          <span class=\"muted\">부산</span>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </a>\n");
      out.write("\n");
      out.write("    <a class=\"card product\" href=\"#\"\n");
      out.write("       data-title=\"롤랜드 디지털피아노 FP-30X\"\n");
      out.write("       data-brand=\"Roland\"\n");
      out.write("       data-city=\"대구\">\n");
      out.write("      <div class=\"thumb\"></div>\n");
      out.write("      <div class=\"meta\">\n");
      out.write("        <h3>롤랜드 디지털피아노 FP-30X</h3>\n");
      out.write("        <p class=\"muted\">Roland</p>\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <span class=\"price\">680,000원</span>\n");
      out.write("          <span class=\"tag\">good</span>\n");
      out.write("          <span class=\"muted\">대구</span>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </a>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<section id=\"features\" class=\"section\">\n");
      out.write("  <h2>왜 소리집인가</h2>\n");
      out.write("  <div class=\"grid-3\">\n");
      out.write("    <a class=\"card\" href=\"#\">\n");
      out.write("      <h3>악기 특화 검색</h3>\n");
      out.write("      <p>브랜드, 모델, 상태, 도시, 가격으로 정밀 필터를 제공합니다.</p>\n");
      out.write("    </a>\n");
      out.write("    <a class=\"card\" href=\"#\">\n");
      out.write("      <h3>안심 거래 가이드</h3>\n");
      out.write("      <p>대면 체크리스트와 직거래 안전 수칙으로 분쟁을 줄입니다.</p>\n");
      out.write("    </a>\n");
      out.write("    <a class=\"card\" href=\"#\">\n");
      out.write("      <h3>투명한 매물 정보</h3>\n");
      out.write("      <p>실사진, 상태표기, 점검 내역을 한눈에 확인할 수 있습니다.</p>\n");
      out.write("    </a>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer class=\"footer\">\n");
      out.write("  <div>© ");
      out.print( java.time.Year.now() );
      out.write(" sorizip</div>\n");
      out.write("  <div>문의: support@sorizip.example</div>\n");
      out.write("</footer>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
