/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2025-11-24 02:29:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("  <title>로그인 – 소리집 sorizip</title>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n");
      out.write("  <!-- 공통 네비/버튼 스타일 재사용 -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/index.css\" />\n");
      out.write("  <style>\n");
      out.write("    /* 로그인 화면 전용 레이아웃 */\n");
      out.write("\n");
      out.write("    .auth-wrapper {\n");
      out.write("      min-height: calc(100vh - 60px);\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("      justify-content: center;\n");
      out.write("      padding: 40px 18px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .auth-card {\n");
      out.write("      width: 100%;\n");
      out.write("      max-width: 360px;\n");
      out.write("      border-radius: 16px;\n");
      out.write("      border: 1px solid #eee;\n");
      out.write("      background: #fff;\n");
      out.write("      padding: 24px 22px 22px;\n");
      out.write("      box-shadow: 0 4px 18px rgba(0, 0, 0, 0.06);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .auth-title {\n");
      out.write("      margin: 0 0 4px;\n");
      out.write("      font-size: 1.2rem;\n");
      out.write("      font-weight: 600;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .auth-sub {\n");
      out.write("      margin: 0 0 18px;\n");
      out.write("      font-size: 0.9rem;\n");
      out.write("      color: #777;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .auth-field {\n");
      out.write("      display: flex;\n");
      out.write("      flex-direction: column;\n");
      out.write("      gap: 4px;\n");
      out.write("      margin-bottom: 14px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .auth-label {\n");
      out.write("      font-size: 0.85rem;\n");
      out.write("      color: #555;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .auth-input {\n");
      out.write("      padding: 8px 10px;\n");
      out.write("      border-radius: 8px;\n");
      out.write("      border: 1px solid #ccc;\n");
      out.write("      font-size: 0.95rem;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .auth-input:focus {\n");
      out.write("      outline: none;\n");
      out.write("      border-color: #ff8a00;\n");
      out.write("      box-shadow: 0 0 0 1px #ffedd5;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .auth-actions {\n");
      out.write("      margin-top: 10px;\n");
      out.write("      display: flex;\n");
      out.write("      flex-direction: column;\n");
      out.write("      gap: 8px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn.full {\n");
      out.write("      width: 100%;\n");
      out.write("      text-align: center;\n");
      out.write("      display: inline-block;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .auth-helper {\n");
      out.write("      margin-top: 10px;\n");
      out.write("      font-size: 0.8rem;\n");
      out.write("      color: #999;\n");
      out.write("      text-align: center;\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<header class=\"nav\">\n");
      out.write("  <a href=\"index.jsp\" class=\"brand\">소리집 <span class=\"sub\">sorizip</span></a>\n");
      out.write("  <nav>\n");
      out.write("    <a href=\"index.jsp#features\">서비스 소개</a>\n");
      out.write("    <a href=\"index.jsp#categories\">카테고리</a>\n");
      out.write("    <a href=\"index.jsp#market\">추천 매물</a>\n");
      out.write("    <a href=\"index.jsp#cta\">시작하기</a>\n");
      out.write("    <a href=\"login.jsp\" style=\"color: #FF6B35; font-weight: 600;\">+ 매물 등록</a>\n");
      out.write("  </nav>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<section class=\"auth-wrapper\">\n");
      out.write("  <form class=\"auth-card\" method=\"get\" action=\"new.jsp\">\n");
      out.write("    <h1 class=\"auth-title\">로그인</h1>\n");
      out.write("    <p class=\"auth-sub\">매물을 등록하려면 먼저 로그인해주세요.</p>\n");
      out.write("\n");
      out.write("    <div class=\"auth-field\">\n");
      out.write("      <label class=\"auth-label\" for=\"userId\">아이디</label>\n");
      out.write("      <input\n");
      out.write("        type=\"text\"\n");
      out.write("        id=\"userId\"\n");
      out.write("        name=\"userId\"\n");
      out.write("        class=\"auth-input\"\n");
      out.write("        placeholder=\"아이디를 입력하세요\"\n");
      out.write("        required\n");
      out.write("      />\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"auth-field\">\n");
      out.write("      <label class=\"auth-label\" for=\"userPw\">비밀번호</label>\n");
      out.write("      <input\n");
      out.write("        type=\"password\"\n");
      out.write("        id=\"userPw\"\n");
      out.write("        name=\"userPw\"\n");
      out.write("        class=\"auth-input\"\n");
      out.write("        placeholder=\"비밀번호를 입력하세요\"\n");
      out.write("        required\n");
      out.write("      />\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"auth-actions\">\n");
      out.write("      <button type=\"submit\" class=\"btn primary full\">로그인</button>\n");
      out.write("      <a href=\"index.jsp\" class=\"btn ghost full\">메인으로 돌아가기</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <p class=\"auth-helper\">\n");
      out.write("      실제 인증 로직은 추후 DB 계정과 연동할 수 있습니다.\n");
      out.write("    </p>\n");
      out.write("  </form>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer class=\"footer\">\n");
      out.write("  <div>© ");
      out.print( java.time.Year.now() );
      out.write(" sorizip</div>\n");
      out.write("  <div>문의: support@sorizip.example</div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
