/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2025-11-24 13:31:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.example.web.Db;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

public final class new_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
    org.apache.jasper.runtime.JspSourceImports,
    org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory = jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String, java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.example.web.Db");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String, java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext())
              .getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory
              .getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request,
      final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow", "GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow", "GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED,
            "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
          null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

      request.setCharacterEncoding("UTF-8");

      // 세션에 저장된 사용자 ID를 사용 (로그인 필요)
      Integer currentUserId = (Integer) session.getAttribute("userId");
      if (currentUserId == null) {
        response.sendRedirect("login.jsp");
        return;
      }

      // 폼 제출 처리
      String action = request.getParameter("action");
      if ("submit".equals(action)) {
        String title = request.getParameter("title");
        String description = request.getParameter("description");
        String priceStr = request.getParameter("price");
        String[] categoryIds = request.getParameterValues("categories");

        if (title != null && !title.trim().isEmpty() && priceStr != null && !priceStr.trim().isEmpty()) {
          try {
            int price = Integer.parseInt(priceStr);

            // sell_post 테이블에 insert
            String insertPostSql = "INSERT INTO sell_post (title, description, price, author_id) VALUES (?, ?, ?, ?)";
            Db.execute(insertPostSql, title, description, price, currentUserId);

            // 방금 insert한 id 가져오기
            String getIdSql = "SELECT LAST_INSERT_ID() as id";
            int postId = Db.query(getIdSql, (ResultSet rs) -> {
              if (rs.next()) {
                return rs.getInt("id");
              }
              return -1;
            });

            // 카테고리 연결
            if (categoryIds != null && categoryIds.length > 0 && postId > 0) {
              String insertCategorySql = "INSERT INTO sell_post_category (sell_post_id, category_id) VALUES (?, ?)";
              for (String categoryId : categoryIds) {
                Db.execute(insertCategorySql, postId, Integer.parseInt(categoryId));
              }
            }

            // 작성 완료 후 상세 페이지로 리다이렉트
            if (postId > 0) {
              response.sendRedirect("show.jsp?id=" + postId);
              return;
            }
          } catch (Exception e) {
            e.printStackTrace();
          }
        }
      }

      // DB에서 카테고리 목록 가져오기
      class Category {
        final int id;
        final String name;

        Category(int id, String name) {
          this.id = id;
          this.name = name;
        }
      }

      List<Category> categories = new ArrayList<>();
      try {
        categories = Db.query("SELECT id, name FROM category ORDER BY name", (ResultSet rs) -> {
          List<Category> result = new ArrayList<>();
          while (rs.next()) {
            result.add(new Category(rs.getInt("id"), rs.getString("name")));
          }
          return result;
        });
      } catch (Exception e) {
        e.printStackTrace();
      }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("  <title>매물 등록 – 소리집 sorizip</title>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/search.css\" />\n");
      out.write("  <style>\n");
      out.write("    .form-container {\n");
      out.write("      max-width: 800px;\n");
      out.write("      margin: 0 auto;\n");
      out.write("      padding: 40px 20px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .form-header {\n");
      out.write("      margin-bottom: 32px;\n");
      out.write("      border-bottom: 2px solid #f0f0f0;\n");
      out.write("      padding-bottom: 20px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .form-title {\n");
      out.write("      font-size: 2em;\n");
      out.write("      font-weight: bold;\n");
      out.write("      color: #333;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .form-group {\n");
      out.write("      margin-bottom: 24px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .form-label {\n");
      out.write("      display: block;\n");
      out.write("      font-weight: 600;\n");
      out.write("      margin-bottom: 8px;\n");
      out.write("      color: #444;\n");
      out.write("      font-size: 1.1em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .form-label .required {\n");
      out.write("      color: #FF6B35;\n");
      out.write("      margin-left: 4px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .form-input,\n");
      out.write("    .form-textarea {\n");
      out.write("      width: 100%;\n");
      out.write("      padding: 12px;\n");
      out.write("      border: 2px solid #ddd;\n");
      out.write("      border-radius: 6px;\n");
      out.write("      font-size: 1em;\n");
      out.write("      transition: border-color 0.2s;\n");
      out.write("      box-sizing: border-box;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .form-input:focus,\n");
      out.write("    .form-textarea:focus {\n");
      out.write("      outline: none;\n");
      out.write("      border-color: #FF6B35;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .form-textarea {\n");
      out.write("      min-height: 200px;\n");
      out.write("      resize: vertical;\n");
      out.write("      font-family: inherit;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .form-hint {\n");
      out.write("      font-size: 0.9em;\n");
      out.write("      color: #666;\n");
      out.write("      margin-top: 6px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .checkbox-group {\n");
      out.write("      display: grid;\n");
      out.write("      grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));\n");
      out.write("      gap: 12px;\n");
      out.write("      margin-top: 12px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .checkbox-item {\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .checkbox-item input[type=\"checkbox\"] {\n");
      out.write("      width: 18px;\n");
      out.write("      height: 18px;\n");
      out.write("      margin-right: 8px;\n");
      out.write("      cursor: pointer;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .checkbox-item label {\n");
      out.write("      cursor: pointer;\n");
      out.write("      user-select: none;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .form-actions {\n");
      out.write("      display: flex;\n");
      out.write("      gap: 12px;\n");
      out.write("      margin-top: 32px;\n");
      out.write("      padding-top: 24px;\n");
      out.write("      border-top: 2px solid #f0f0f0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn {\n");
      out.write("      padding: 12px 24px;\n");
      out.write("      border: none;\n");
      out.write("      border-radius: 6px;\n");
      out.write("      font-size: 1em;\n");
      out.write("      font-weight: 600;\n");
      out.write("      cursor: pointer;\n");
      out.write("      transition: all 0.2s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn-primary {\n");
      out.write("      background: #FF6B35;\n");
      out.write("      color: white;\n");
      out.write("      flex: 1;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn-primary:hover {\n");
      out.write("      background: #e55a2a;\n");
      out.write("      transform: translateY(-1px);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn-secondary {\n");
      out.write("      background: #f0f0f0;\n");
      out.write("      color: #333;\n");
      out.write("      padding: 12px 24px;\n");
      out.write("      text-decoration: none;\n");
      out.write("      display: inline-block;\n");
      out.write("      text-align: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn-secondary:hover {\n");
      out.write("      background: #e0e0e0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .back-link {\n");
      out.write("      display: inline-block;\n");
      out.write("      margin-bottom: 20px;\n");
      out.write("      color: #FF6B35;\n");
      out.write("      text-decoration: none;\n");
      out.write("      font-weight: 500;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .back-link:hover {\n");
      out.write("      text-decoration: underline;\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<header class=\"nav\">\n");
      out.write("  <a href=\"index.jsp\" class=\"brand\">소리집 <span class=\"sub\">sorizip</span></a>\n");
      out.write("  <nav>\n");
      out.write("    <a href=\"index.jsp#features\">서비스 소개</a>\n");
      out.write("    <a href=\"index.jsp#categories\">카테고리</a>\n");
      out.write("    <a href=\"index.jsp#market\">추천 매물</a>\n");
      out.write("    <a href=\"search.jsp\">검색</a>\n");
      out.write("  </nav>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<div class=\"form-container\">\n");
      out.write("  <a href=\"search.jsp\" class=\"back-link\">← 목록으로 돌아가기</a>\n");
      out.write("\n");
      out.write("  <div class=\"form-header\">\n");
      out.write("    <h1 class=\"form-title\">악기 매물 등록</h1>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <form method=\"post\" action=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("    <input type=\"hidden\" name=\"action\" value=\"create\" />\n");
      out.write("\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label class=\"form-label\">\n");
      out.write("        제목<span class=\"required\">*</span>\n");
      out.write("      </label>\n");
      out.write("      <input\n");
      out.write("        type=\"text\"\n");
      out.write("        name=\"title\"\n");
      out.write("        class=\"form-input\"\n");
      out.write("        placeholder=\"예) 야마하 업라이트 피아노 U1\"\n");
      out.write("        required\n");
      out.write("      />\n");
      out.write("      <div class=\"form-hint\">악기 이름과 모델명을 간단히 입력해주세요</div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label class=\"form-label\">\n");
      out.write("        가격 (원)<span class=\"required\">*</span>\n");
      out.write("      </label>\n");
      out.write("      <input\n");
      out.write("        type=\"number\"\n");
      out.write("        name=\"price\"\n");
      out.write("        class=\"form-input\"\n");
      out.write("        placeholder=\"예) 1800000\"\n");
      out.write("        min=\"0\"\n");
      out.write("        step=\"1000\"\n");
      out.write("        required\n");
      out.write("      />\n");
      out.write("      <div class=\"form-hint\">숫자만 입력해주세요 (단위: 원)</div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label class=\"form-label\">\n");
      out.write("        카테고리<span class=\"required\">*</span>\n");
      out.write("      </label>\n");
      out.write("      <div class=\"checkbox-group\">\n");
      out.write("        ");
      for (Category category : categories) {
        out.write("\n");
        out.write("        <div class=\"checkbox-item\">\n");
        out.write("          <input\n");
        out.write("            type=\"checkbox\"\n");
        out.write("            name=\"categories\"\n");
        out.write("            id=\"cat_");
        out.print(category.id);
        out.write("\"\n");
        out.write("            value=\"");
        out.print(category.id);
        out.write("\"\n");
        out.write("          />\n");
        out.write("          <label for=\"cat_");
        out.print(category.id);
        out.write('"');
        out.write('>');
        out.print(category.name);
        out.write("</label>\n");
        out.write("        </div>\n");
        out.write("        ");
      }
      out.write("\n");
      out.write("      </div>\n");
      out.write("      <div class=\"form-hint\">하나 이상의 카테고리를 선택해주세요</div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label class=\"form-label\">\n");
      out.write("        이미지 업로드\n");
      out.write("      </label>\n");
      out.write("      <input\n");
      out.write("        type=\"file\"\n");
      out.write("        name=\"images\"\n");
      out.write("        class=\"form-input\"\n");
      out.write("        accept=\"image/*\"\n");
      out.write("        multiple\n");
      out.write("      />\n");
      out.write("      <div class=\"form-hint\">여러 개의 이미지를 선택할 수 있습니다 (최대 10MB per file)</div>\n");
      out.write(
          "      <div id=\"imagePreviewContainer\" style=\"display: flex; flex-wrap: wrap; gap: 10px; margin-top: 12px;\"></div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label class=\"form-label\">\n");
      out.write("        상세 설명\n");
      out.write("      </label>\n");
      out.write("      <textarea\n");
      out.write("        name=\"description\"\n");
      out.write("        class=\"form-textarea\"\n");
      out.write("        placeholder=\"악기의 상태, 구매 시기, 사용 기간 등을 자세히 작성해주세요\"\n");
      out.write("      ></textarea>\n");
      out.write("      <div class=\"form-hint\">구매자가 알아야 할 정보를 상세히 작성해주세요</div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"form-actions\">\n");
      out.write("      <a href=\"search.jsp\" class=\"btn btn-secondary\">취소</a>\n");
      out.write("      <button type=\"submit\" class=\"btn btn-primary\">등록하기</button>\n");
      out.write("    </div>\n");
      out.write("  </form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<footer class=\"footer\">\n");
      out.write("  <div>© ");
      out.print(java.time.Year.now());
      out.write(" sorizip</div>\n");
      out.write("  <div>문의: support@sorizip.example</div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  // 폼 제출 전 유효성 검사\n");
      out.write("  document.querySelector('form').addEventListener('submit', function(e) {\n");
      out.write("    const categories = document.querySelectorAll('input[name=\"categories\"]:checked');\n");
      out.write("    if (categories.length === 0) {\n");
      out.write("      e.preventDefault();\n");
      out.write("      alert('최소 하나의 카테고리를 선택해주세요.');\n");
      out.write("      return false;\n");
      out.write("    }\n");
      out.write("  });\n");
      out.write("\n");
      out.write("  // 이미지 미리보기\n");
      out.write("  document.querySelector('input[name=\"images\"]').addEventListener('change', function(e) {\n");
      out.write("    const previewContainer = document.getElementById('imagePreviewContainer');\n");
      out.write("    previewContainer.innerHTML = '';\n");
      out.write("\n");
      out.write("    const files = e.target.files;\n");
      out.write("    for (let i = 0; i < files.length; i++) {\n");
      out.write("      const file = files[i];\n");
      out.write("      if (file.type.startsWith('image/')) {\n");
      out.write("        const reader = new FileReader();\n");
      out.write("        reader.onload = function(event) {\n");
      out.write("          const img = document.createElement('img');\n");
      out.write("          img.src = event.target.result;\n");
      out.write("          img.style.width = '120px';\n");
      out.write("          img.style.height = '120px';\n");
      out.write("          img.style.objectFit = 'cover';\n");
      out.write("          img.style.borderRadius = '8px';\n");
      out.write("          img.style.border = '2px solid #ddd';\n");
      out.write("          previewContainer.appendChild(img);\n");
      out.write("        };\n");
      out.write("        reader.readAsDataURL(file);\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("  });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)) {
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {
          }
        if (_jspx_page_context != null)
          _jspx_page_context.handlePageException(t);
        else
          throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
