/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2025-11-24 01:15:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.example.web.Db;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


  // 가격을 만원 단위로 포맷팅하는 함수
  String formatPrice(int price) {
    double manwon = price / 10000.0;
    if (manwon == (int) manwon) {
      return (int) manwon + "만원";
    } else {
      return String.format("%.1f만원", manwon);
    }
  }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.example.web.Db");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

  request.setCharacterEncoding("UTF-8");

  String q = request.getParameter("q");
  if (q == null) q = "";
  String keyword = q.trim();

  String categoryParam = request.getParameter("category");
  if (categoryParam == null) categoryParam = "";
  String selectedCategory = categoryParam.trim();

  // DB에서 판매 게시글 가져오기
  class Post {
    int id;
    String title;
    String description;
    int price;
    String authorEmail;
    String categories;

    Post(int id, String title, String description, int price, String authorEmail, String categories) {
      this.id = id;
      this.title = title;
      this.description = description;
      this.price = price;
      this.authorEmail = authorEmail;
      this.categories = categories;
    }
  }

  // DB에서 카테고리 목록 가져오기
  List<String> categories = new ArrayList<>();
  try {
    categories = Db.query("SELECT name FROM category ORDER BY name", (ResultSet rs) -> {
      List<String> result = new ArrayList<>();
      while (rs.next()) {
        result.add(rs.getString("name"));
      }
      return result;
    });
  } catch (Exception e) {
    e.printStackTrace();
  }

  List<Post> posts = new ArrayList<>();
  try {
    String sql;
    if (!selectedCategory.isEmpty()) {
      // 카테고리 필터가 있을 때
      sql =
        "SELECT sp.id, sp.title, sp.description, sp.price, u.email, " +
        "       GROUP_CONCAT(c.name SEPARATOR ', ') as categories " +
        "FROM sell_post sp " +
        "LEFT JOIN user u ON sp.author_id = u.id " +
        "LEFT JOIN sell_post_category spc ON sp.id = spc.sell_post_id " +
        "LEFT JOIN category c ON spc.category_id = c.id " +
        "WHERE sp.id IN ( " +
        "  SELECT DISTINCT sp2.id FROM sell_post sp2 " +
        "  JOIN sell_post_category spc2 ON sp2.id = spc2.sell_post_id " +
        "  JOIN category c2 ON spc2.category_id = c2.id " +
        "  WHERE c2.name = ? " +
        ") " +
        "GROUP BY sp.id, sp.title, sp.description, sp.price, u.email " +
        "ORDER BY sp.created_at DESC";

      posts = Db.query(sql, (ResultSet rs) -> {
        List<Post> result = new ArrayList<>();
        while (rs.next()) {
          result.add(new Post(
            rs.getInt("id"),
            rs.getString("title"),
            rs.getString("description"),
            rs.getInt("price"),
            rs.getString("email"),
            rs.getString("categories")
          ));
        }
        return result;
      }, selectedCategory);
    } else {
      // 전체 조회
      sql =
        "SELECT sp.id, sp.title, sp.description, sp.price, u.email, " +
        "       GROUP_CONCAT(c.name SEPARATOR ', ') as categories " +
        "FROM sell_post sp " +
        "LEFT JOIN user u ON sp.author_id = u.id " +
        "LEFT JOIN sell_post_category spc ON sp.id = spc.sell_post_id " +
        "LEFT JOIN category c ON spc.category_id = c.id " +
        "GROUP BY sp.id, sp.title, sp.description, sp.price, u.email " +
        "ORDER BY sp.created_at DESC";

      posts = Db.query(sql, (ResultSet rs) -> {
        List<Post> result = new ArrayList<>();
        while (rs.next()) {
          result.add(new Post(
            rs.getInt("id"),
            rs.getString("title"),
            rs.getString("description"),
            rs.getInt("price"),
            rs.getString("email"),
            rs.getString("categories")
          ));
        }
        return result;
      });
    }
  } catch (Exception e) {
    e.printStackTrace();
  }

      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("  <title>검색 결과 – 소리집 sorizip</title>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/search.css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<header class=\"nav\">\n");
      out.write("  <a href=\"index.jsp\" class=\"brand\">소리집 <span class=\"sub\">sorizip</span></a>\n");
      out.write("  <nav>\n");
      out.write("    <a href=\"index.jsp#features\">서비스 소개</a>\n");
      out.write("    <a href=\"index.jsp#categories\">카테고리</a>\n");
      out.write("    <a href=\"index.jsp#market\">추천 매물</a>\n");
      out.write("    <a href=\"new.jsp\" style=\"color: #FF6B35; font-weight: 600;\">+ 매물 등록</a>\n");
      out.write("  </nav>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<section class=\"section\">\n");
      out.write("  <h2>검색 결과</h2>\n");
      out.write("\n");
      out.write("  <!-- 상단 검색창 -->\n");
      out.write("  <form class=\"search-bar\" method=\"get\" action=\"search.jsp\">\n");
      out.write("    <input\n");
      out.write("      type=\"text\"\n");
      out.write("      name=\"q\"\n");
      out.write("      id=\"searchInput\"\n");
      out.write("      class=\"search-input\"\n");
      out.write("      placeholder=\"악기 이름, 브랜드, 도시로 검색해보세요\"\n");
      out.write("      value=\"");
      out.print( keyword );
      out.write("\"\n");
      out.write("    />\n");
      out.write("    <button type=\"submit\" class=\"btn primary\">검색</button>\n");
      out.write("  </form>\n");
      out.write("\n");
      out.write("  <!-- 상세 검색 필터 (카테고리만) -->\n");
      out.write("  <div class=\"filter-bar\">\n");
      out.write("  <div class=\"filter-group\">\n");
      out.write("    <span class=\"filter-label\">카테고리</span>\n");
      out.write("\n");
      out.write("    <button type=\"button\"\n");
      out.write("            class=\"chip chip-filter ");
      out.print( selectedCategory.isEmpty() ? "active" : "" );
      out.write("\"\n");
      out.write("            data-category=\"\">\n");
      out.write("      전체\n");
      out.write("    </button>\n");
      out.write("\n");
      out.write("    ");
 for (String category : categories) { 
      out.write("\n");
      out.write("    <button type=\"button\"\n");
      out.write("            class=\"chip chip-filter ");
      out.print( category.equals(selectedCategory) ? "active" : "" );
      out.write("\"\n");
      out.write("            data-category=\"");
      out.print( category );
      out.write("\">\n");
      out.write("      ");
      out.print( category );
      out.write("\n");
      out.write("    </button>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("  <p class=\"muted\" style=\"margin-top:6px;\">\n");
      out.write("    ");
 if (!keyword.isEmpty()) { 
      out.write("\n");
      out.write("      \"<strong>");
      out.print( keyword );
      out.write("</strong>\"에 대한 검색 결과\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("      검색어와 카테고리 필터를 조합해 원하는 악기를 찾아보세요.\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </p>\n");
      out.write("\n");
      out.write("  <hr style=\"margin:16px 0; border:none; border-top:1px solid #eee;\" />\n");
      out.write("\n");
      out.write("  <!-- 결과 카드 (DB에서 동적 생성) -->\n");
      out.write("  <div class=\"grid-3\" id=\"resultGrid\">\n");
      out.write("    ");
 for (Post post : posts) {
       String categoriesDisplay = post.categories != null ? post.categories : "미분류";
       String priceFormatted = formatPrice(post.price);
    
      out.write("\n");
      out.write("    <a class=\"card product\"\n");
      out.write("       href=\"show.jsp?id=");
      out.print( post.id );
      out.write("\"\n");
      out.write("       data-category=\"");
      out.print( categoriesDisplay );
      out.write("\"\n");
      out.write("       data-title=\"");
      out.print( post.title );
      out.write("\">\n");
      out.write("      <div class=\"thumb\"></div>\n");
      out.write("      <div class=\"meta\">\n");
      out.write("        <h3>");
      out.print( post.title );
      out.write("</h3>\n");
      out.write("        <p class=\"muted\">");
      out.print( categoriesDisplay );
      out.write("</p>\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <span class=\"price\">");
      out.print( priceFormatted );
      out.write("</span>\n");
      out.write("        </div>\n");
      out.write("        ");
 if (post.description != null && !post.description.isEmpty()) { 
      out.write("\n");
      out.write("        <p class=\"muted\" style=\"font-size:0.85em; margin-top:4px;\">");
      out.print( post.description );
      out.write("</p>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </a>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <p id=\"emptyMessage\" style=\"display:none; margin-top:10px;\">\n");
      out.write("    조건에 맞는 매물이 없습니다. 검색어와 카테고리를 바꿔보세요.\n");
      out.write("  </p>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer class=\"footer\">\n");
      out.write("  <div>© ");
      out.print( java.time.Year.now() );
      out.write(" sorizip</div>\n");
      out.write("  <div>문의: support@sorizip.example</div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  (function () {\n");
      out.write("    const keywordInput = document.getElementById(\"searchInput\");\n");
      out.write("    const categoryChips = document.querySelectorAll(\".chip-filter\");\n");
      out.write("    const cards = document.querySelectorAll(\".card.product\");\n");
      out.write("    const emptyMessage = document.getElementById(\"emptyMessage\");\n");
      out.write("\n");
      out.write("    let currentCategory = \"");
      out.print( selectedCategory );
      out.write("\";\n");
      out.write("\n");
      out.write("    function applyFilter() {\n");
      out.write("      const q = (keywordInput.value || \"\").trim().toLowerCase();\n");
      out.write("      let visibleCount = 0;\n");
      out.write("\n");
      out.write("      cards.forEach((card) => {\n");
      out.write("        const title = (card.dataset.title || \"\").toLowerCase();\n");
      out.write("        const category = card.dataset.category || \"\";\n");
      out.write("\n");
      out.write("        const text = title + \" \" + category;\n");
      out.write("\n");
      out.write("        // 키워드만 클라이언트 사이드에서 필터링 (카테고리는 서버에서 이미 필터링됨)\n");
      out.write("        const matchKeyword = !q || text.includes(q);\n");
      out.write("\n");
      out.write("        card.style.display = matchKeyword ? \"\" : \"none\";\n");
      out.write("        if (matchKeyword) visibleCount++;\n");
      out.write("      });\n");
      out.write("\n");
      out.write("      emptyMessage.style.display = visibleCount === 0 ? \"block\" : \"none\";\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // 카테고리 칩 클릭 - 서버 사이드 필터링을 위해 페이지 리로드\n");
      out.write("    categoryChips.forEach((chip) => {\n");
      out.write("      chip.addEventListener(\"click\", () => {\n");
      out.write("        const category = chip.dataset.category || \"\";\n");
      out.write("        const currentKeyword = keywordInput.value.trim();\n");
      out.write("\n");
      out.write("        // URL 파라미터 구성\n");
      out.write("        let url = \"search.jsp?\";\n");
      out.write("        if (currentKeyword) {\n");
      out.write("          url += \"q=\" + encodeURIComponent(currentKeyword) + \"&\";\n");
      out.write("        }\n");
      out.write("        if (category) {\n");
      out.write("          url += \"category=\" + encodeURIComponent(category);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        // 페이지 이동\n");
      out.write("        window.location.href = url;\n");
      out.write("      });\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    // 키워드 변경\n");
      out.write("    keywordInput.addEventListener(\"input\", applyFilter);\n");
      out.write("\n");
      out.write("    document.addEventListener(\"DOMContentLoaded\", applyFilter);\n");
      out.write("  })();\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
