/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2025-11-22 13:37:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

  request.setCharacterEncoding("UTF-8");
  String q = request.getParameter("q");
  if (q == null) q = "";
  String keyword = q.trim();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("  <title>검색 결과 – 소리집 sorizip</title>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/styles.css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<header class=\"nav\">\n");
      out.write("  <div class=\"brand\">소리집 <span class=\"sub\">sorizip</span></div>\n");
      out.write("  <nav>\n");
      out.write("    <a href=\"index.jsp#features\">서비스 소개</a>\n");
      out.write("    <a href=\"index.jsp#categories\">카테고리</a>\n");
      out.write("    <a href=\"index.jsp#market\">추천 매물</a>\n");
      out.write("    <a href=\"index.jsp#cta\">시작하기</a>\n");
      out.write("  </nav>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<section class=\"section\">\n");
      out.write("  <h2>검색 결과</h2>\n");
      out.write("\n");
      out.write("  <!-- 검색어 다시 입력할 수 있는 작은 검색창 -->\n");
      out.write("  <form class=\"search-bar\" method=\"get\" action=\"search.jsp\">\n");
      out.write("    <input\n");
      out.write("      type=\"text\"\n");
      out.write("      name=\"q\"\n");
      out.write("      class=\"search-input\"\n");
      out.write("      placeholder=\"악기 이름, 브랜드, 도시로 검색해보세요\"\n");
      out.write("      value=\"");
      out.print( keyword );
      out.write("\"\n");
      out.write("    />\n");
      out.write("    <button type=\"submit\" class=\"btn primary\">검색</button>\n");
      out.write("  </form>\n");
      out.write("\n");
      out.write("  ");

    // 나중에: 여기서 DAO로 DB 검색하면 됨.
    // 지금은 화면 구성을 위해 더미 결과 3개만 조건부로 보여줄게.

    boolean hasKeyword = !keyword.isEmpty();
    // 대충 '야마하' 검색했다고 치고, 있을 때는 3개, 없으면 0개 예시
    int dummyCount = hasKeyword ? 3 : 0;
  
      out.write("\n");
      out.write("\n");
      out.write("  <p class=\"muted\" style=\"margin-top:6px;\">\n");
      out.write("    ");
 if (hasKeyword) { 
      out.write("\n");
      out.write("      \"<strong>");
      out.print( keyword );
      out.write("</strong>\" 검색 결과 <strong>");
      out.print( dummyCount );
      out.write("</strong>건\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("      검색어를 입력해 주세요.\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </p>\n");
      out.write("\n");
      out.write("  <hr style=\"margin:16px 0; border:none; border-top:1px solid #eee;\" />\n");
      out.write("\n");
      out.write("  ");
 if (!hasKeyword) { 
      out.write("\n");
      out.write("    <p class=\"muted\">위 입력창에 원하는 악기를 입력해 검색해보세요.</p>\n");
      out.write("  ");
 } else if (dummyCount == 0) { 
      out.write("\n");
      out.write("    <p>일치하는 매물이 없습니다. 다른 키워드로 다시 검색해 보세요.</p>\n");
      out.write("  ");
 } else { 
      out.write("\n");
      out.write("    <div class=\"grid-3\">\n");
      out.write("\n");
      out.write("      <!-- 검색 결과 카드 예시 1 -->\n");
      out.write("      <a class=\"card product\" href=\"#\">\n");
      out.write("        <div class=\"thumb\"></div>\n");
      out.write("        <div class=\"meta\">\n");
      out.write("          <h3>야마하 업라이트 U1</h3>\n");
      out.write("          <p class=\"muted\">Yamaha · 서울</p>\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <span class=\"price\">1,800,000원</span>\n");
      out.write("            <span class=\"tag\">good</span>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </a>\n");
      out.write("\n");
      out.write("      <!-- 검색 결과 카드 예시 2 -->\n");
      out.write("      <a class=\"card product\" href=\"#\">\n");
      out.write("        <div class=\"thumb\"></div>\n");
      out.write("        <div class=\"meta\">\n");
      out.write("          <h3>야마하 어쿠스틱 기타 FG800</h3>\n");
      out.write("          <p class=\"muted\">Yamaha · 대구</p>\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <span class=\"price\">220,000원</span>\n");
      out.write("            <span class=\"tag\">like-new</span>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </a>\n");
      out.write("\n");
      out.write("      <!-- 검색 결과 카드 예시 3 -->\n");
      out.write("      <a class=\"card product\" href=\"#\">\n");
      out.write("        <div class=\"thumb\"></div>\n");
      out.write("        <div class=\"meta\">\n");
      out.write("          <h3>야마하 디지털피아노 P-125</h3>\n");
      out.write("          <p class=\"muted\">Yamaha · 부산</p>\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <span class=\"price\">550,000원</span>\n");
      out.write("            <span class=\"tag\">good</span>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </a>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer class=\"footer\">\n");
      out.write("  <div>© ");
      out.print( java.time.Year.now() );
      out.write(" sorizip</div>\n");
      out.write("  <div>문의: support@sorizip.example</div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
