/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2025-11-22 14:09:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

  request.setCharacterEncoding("UTF-8");
  String q = request.getParameter("q");
  if (q == null) q = "";
  String keyword = q.trim();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("  <title>검색 결과 – 소리집 sorizip</title>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/search.css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<header class=\"nav\">\n");
      out.write("  <a href=\"index.jsp\" class=\"brand\">소리집 <span class=\"sub\">sorizip</span></a>\n");
      out.write("  <nav>\n");
      out.write("    <a href=\"index.jsp#features\">서비스 소개</a>\n");
      out.write("    <a href=\"index.jsp#categories\">카테고리</a>\n");
      out.write("    <a href=\"index.jsp#market\">추천 매물</a>\n");
      out.write("    <a href=\"index.jsp#cta\">시작하기</a>\n");
      out.write("  </nav>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<section class=\"section\">\n");
      out.write("  <h2>검색 결과</h2>\n");
      out.write("\n");
      out.write("  <!-- 상단 검색창 -->\n");
      out.write("  <form class=\"search-bar\" method=\"get\" action=\"search.jsp\">\n");
      out.write("    <input\n");
      out.write("      type=\"text\"\n");
      out.write("      name=\"q\"\n");
      out.write("      id=\"searchInput\"\n");
      out.write("      class=\"search-input\"\n");
      out.write("      placeholder=\"악기 이름, 브랜드, 도시로 검색해보세요\"\n");
      out.write("      value=\"");
      out.print( keyword );
      out.write("\"\n");
      out.write("    />\n");
      out.write("    <button type=\"submit\" class=\"btn primary\">검색</button>\n");
      out.write("  </form>\n");
      out.write("\n");
      out.write("  <!-- 상세 검색 필터 (카테고리만) -->\n");
      out.write("  <div class=\"filter-bar\">\n");
      out.write("    <div class=\"filter-group\">\n");
      out.write("      <span class=\"filter-label\">카테고리</span>\n");
      out.write("      <button type=\"button\" class=\"chip chip-filter active\" data-category=\"\">전체</button>\n");
      out.write("      <button type=\"button\" class=\"chip chip-filter\" data-category=\"어쿠스틱 기타\">어쿠스틱 기타</button>\n");
      out.write("      <button type=\"button\" class=\"chip chip-filter\" data-category=\"일렉 기타\">일렉 기타</button>\n");
      out.write("      <button type=\"button\" class=\"chip chip-filter\" data-category=\"베이스\">베이스</button>\n");
      out.write("      <button type=\"button\" class=\"chip chip-filter\" data-category=\"피아노\">피아노</button>\n");
      out.write("      <button type=\"button\" class=\"chip chip-filter\" data-category=\"신디사이저\">신디사이저</button>\n");
      out.write("      <button type=\"button\" class=\"chip chip-filter\" data-category=\"관악기\">관악기</button>\n");
      out.write("      <button type=\"button\" class=\"chip chip-filter\" data-category=\"드럼\">드럼</button>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <p class=\"muted\" style=\"margin-top:6px;\">\n");
      out.write("    ");
 if (!keyword.isEmpty()) { 
      out.write("\n");
      out.write("      \"<strong>");
      out.print( keyword );
      out.write("</strong>\"에 대한 검색 결과\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("      검색어와 카테고리 필터를 조합해 원하는 악기를 찾아보세요.\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </p>\n");
      out.write("\n");
      out.write("  <hr style=\"margin:16px 0; border:none; border-top:1px solid #eee;\" />\n");
      out.write("\n");
      out.write("  <!-- 결과 카드 (지금은 예시 데이터) -->\n");
      out.write("  <div class=\"grid-3\" id=\"resultGrid\">\n");
      out.write("    <a class=\"card product\"\n");
      out.write("       href=\"#\"\n");
      out.write("       data-category=\"피아노\"\n");
      out.write("       data-brand=\"Yamaha\"\n");
      out.write("       data-city=\"서울\"\n");
      out.write("       data-title=\"야마하 업라이트 U1\">\n");
      out.write("      <div class=\"thumb\"></div>\n");
      out.write("      <div class=\"meta\">\n");
      out.write("        <h3>야마하 업라이트 U1</h3>\n");
      out.write("        <p class=\"muted\">Yamaha · 서울</p>\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <span class=\"price\">1,800,000원</span>\n");
      out.write("          <span class=\"tag\">good</span>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </a>\n");
      out.write("\n");
      out.write("    <a class=\"card product\"\n");
      out.write("       href=\"#\"\n");
      out.write("       data-category=\"일렉 기타\"\n");
      out.write("       data-brand=\"Fender\"\n");
      out.write("       data-city=\"부산\"\n");
      out.write("       data-title=\"펜더 스트라토캐스터\">\n");
      out.write("      <div class=\"thumb\"></div>\n");
      out.write("      <div class=\"meta\">\n");
      out.write("        <h3>펜더 스트라토캐스터</h3>\n");
      out.write("        <p class=\"muted\">Fender · 부산</p>\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <span class=\"price\">950,000원</span>\n");
      out.write("          <span class=\"tag\">like-new</span>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </a>\n");
      out.write("\n");
      out.write("    <a class=\"card product\"\n");
      out.write("       href=\"#\"\n");
      out.write("       data-category=\"피아노\"\n");
      out.write("       data-brand=\"Roland\"\n");
      out.write("       data-city=\"대구\"\n");
      out.write("       data-title=\"롤랜드 디지털피아노 FP-30X\">\n");
      out.write("      <div class=\"thumb\"></div>\n");
      out.write("      <div class=\"meta\">\n");
      out.write("        <h3>롤랜드 디지털피아노 FP-30X</h3>\n");
      out.write("        <p class=\"muted\">Roland · 대구</p>\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <span class=\"price\">680,000원</span>\n");
      out.write("          <span class=\"tag\">good</span>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </a>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <p id=\"emptyMessage\" style=\"display:none; margin-top:10px;\">\n");
      out.write("    조건에 맞는 매물이 없습니다. 검색어와 카테고리를 바꿔보세요.\n");
      out.write("  </p>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer class=\"footer\">\n");
      out.write("  <div>© ");
      out.print( java.time.Year.now() );
      out.write(" sorizip</div>\n");
      out.write("  <div>문의: support@sorizip.example</div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  (function () {\n");
      out.write("    const keywordInput = document.getElementById(\"searchInput\");\n");
      out.write("    const categoryChips = document.querySelectorAll(\".chip-filter\");\n");
      out.write("    const cards = document.querySelectorAll(\".card.product\");\n");
      out.write("    const emptyMessage = document.getElementById(\"emptyMessage\");\n");
      out.write("\n");
      out.write("    let currentCategory = \"\";\n");
      out.write("\n");
      out.write("    function applyFilter() {\n");
      out.write("      const q = (keywordInput.value || \"\").trim().toLowerCase();\n");
      out.write("      let visibleCount = 0;\n");
      out.write("\n");
      out.write("      cards.forEach((card) => {\n");
      out.write("        const title = (card.dataset.title || \"\").toLowerCase();\n");
      out.write("        const brand = (card.dataset.brand || \"\").toLowerCase();\n");
      out.write("        const city = (card.dataset.city || \"\").toLowerCase();\n");
      out.write("        const category = card.dataset.category || \"\";\n");
      out.write("\n");
      out.write("        const text = title + \" \" + brand + \" \" + city;\n");
      out.write("\n");
      out.write("        const matchKeyword = !q || text.includes(q);\n");
      out.write("        const matchCategory = !currentCategory || category === currentCategory;\n");
      out.write("\n");
      out.write("        const show = matchKeyword && matchCategory;\n");
      out.write("        card.style.display = show ? \"\" : \"none\";\n");
      out.write("        if (show) visibleCount++;\n");
      out.write("      });\n");
      out.write("\n");
      out.write("      emptyMessage.style.display = visibleCount === 0 ? \"block\" : \"none\";\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // 카테고리 칩 클릭\n");
      out.write("    categoryChips.forEach((chip) => {\n");
      out.write("      chip.addEventListener(\"click\", () => {\n");
      out.write("        categoryChips.forEach((c) => c.classList.remove(\"active\"));\n");
      out.write("        chip.classList.add(\"active\");\n");
      out.write("        currentCategory = chip.dataset.category || \"\";\n");
      out.write("        applyFilter();\n");
      out.write("      });\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    // 키워드 변경\n");
      out.write("    keywordInput.addEventListener(\"input\", applyFilter);\n");
      out.write("\n");
      out.write("    document.addEventListener(\"DOMContentLoaded\", applyFilter);\n");
      out.write("  })();\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
