/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2025-11-24 02:31:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.example.web.Db;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

public final class show_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
    org.apache.jasper.runtime.JspSourceImports,
    org.apache.jasper.runtime.JspSourceDirectives {

  // 가격을 만원 단위로 포맷팅하는 함수
  String formatPrice(int price) {
    double manwon = price / 10000.0;
    if (manwon == (int) manwon) {
      return (int) manwon + "만원";
    } else {
      return String.format("%.1f만원", manwon);
    }
  }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory = jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String, java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.example.web.Db");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String, java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext())
              .getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory
              .getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request,
      final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow", "GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow", "GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED,
            "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
          null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

      request.setCharacterEncoding("UTF-8");

      String idParam = request.getParameter("id");
      if (idParam == null || idParam.isEmpty()) {
        response.sendRedirect("search.jsp");
        return;
      }

      int postId = Integer.parseInt(idParam);

      // 임시로 user id 1번으로 로그인되어있다고 가정
      int currentUserId = 1;

      // 댓글 작성 처리
      String commentAction = request.getParameter("commentAction");
      if ("submit".equals(commentAction)) {
        String commentContent = request.getParameter("content");
        if (commentContent != null && !commentContent.trim().isEmpty()) {
          try {
            String insertCommentSql = "INSERT INTO sell_post_comment (post_id, user_id, content) VALUES (?, ?, ?)";
            Db.execute(insertCommentSql, postId, currentUserId, commentContent.trim());

            // 방금 작성한 댓글의 ID 가져오기
            String getLastCommentIdSql = "SELECT LAST_INSERT_ID() as id";
            int lastCommentId = Db.query(getLastCommentIdSql, (ResultSet rs) -> {
              if (rs.next()) {
                return rs.getInt("id");
              }
              return -1;
            });

            // 댓글 작성 후 해당 댓글로 스크롤되도록 앵커 추가
            response.sendRedirect("show.jsp?id=" + postId + "#comment-" + lastCommentId);
            return;
          } catch (Exception e) {
            e.printStackTrace();
          }
        }
      }

      // DB에서 게시글 상세 정보 가져오기
      class PostDetail {
        final int id;
        final String title;
        final String description;
        final int price;
        final int authorId;
        final String authorEmail;
        final String categories;
        final String createdAt;

        PostDetail(int id, String title, String description, int price, int authorId, String authorEmail,
            String categories, String createdAt) {
          this.id = id;
          this.title = title;
          this.description = description;
          this.price = price;
          this.authorId = authorId;
          this.authorEmail = authorEmail;
          this.categories = categories;
          this.createdAt = createdAt;
        }
      }

      // 댓글 클래스
      class Comment {
        final int id;
        final int userId;
        final String userEmail;
        final String content;
        final String createdAt;

        Comment(int id, int userId, String userEmail, String content, String createdAt) {
          this.id = id;
          this.userId = userId;
          this.userEmail = userEmail;
          this.content = content;
          this.createdAt = createdAt;
        }
      }

      PostDetail post = null;
      try {
        String sql = "SELECT sp.id, sp.title, sp.description, sp.price, sp.author_id, u.email, " +
            "       GROUP_CONCAT(c.name SEPARATOR ', ') as categories, " +
            "       sp.created_at " +
            "FROM sell_post sp " +
            "LEFT JOIN user u ON sp.author_id = u.id " +
            "LEFT JOIN sell_post_category spc ON sp.id = spc.sell_post_id " +
            "LEFT JOIN category c ON spc.category_id = c.id " +
            "WHERE sp.id = ? " +
            "GROUP BY sp.id, sp.title, sp.description, sp.price, sp.author_id, u.email, sp.created_at";

        post = Db.query(sql, (ResultSet rs) -> {
          if (rs.next()) {
            return new PostDetail(
                rs.getInt("id"),
                rs.getString("title"),
                rs.getString("description"),
                rs.getInt("price"),
                rs.getInt("author_id"),
                rs.getString("email"),
                rs.getString("categories"),
                rs.getString("created_at"));
          }
          return null;
        }, postId);
      } catch (Exception e) {
        e.printStackTrace();
      }

      if (post == null) {
        response.sendRedirect("search.jsp");
        return;
      }

      // 댓글 목록 가져오기
      List<Comment> comments = new ArrayList<>();
      try {
        String commentSql = "SELECT c.id, c.user_id, u.email, c.content, c.created_at " +
            "FROM sell_post_comment c " +
            "LEFT JOIN user u ON c.user_id = u.id " +
            "WHERE c.post_id = ? " +
            "ORDER BY c.created_at ASC";

        comments = Db.query(commentSql, (ResultSet rs) -> {
          List<Comment> result = new ArrayList<>();
          while (rs.next()) {
            result.add(new Comment(
                rs.getInt("id"),
                rs.getInt("user_id"),
                rs.getString("email"),
                rs.getString("content"),
                rs.getString("created_at")));
          }
          return result;
        }, postId);
      } catch (Exception e) {
        e.printStackTrace();
      }

      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("  <title>");
      out.print(post.title);
      out.write(" – 소리집 sorizip</title>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/search.css\" />\n");
      out.write("  <style>\n");
      out.write("    .post-detail {\n");
      out.write("      max-width: 900px;\n");
      out.write("      margin: 0 auto;\n");
      out.write("      padding: 40px 20px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-header {\n");
      out.write("      margin-bottom: 24px;\n");
      out.write("      border-bottom: 2px solid #f0f0f0;\n");
      out.write("      padding-bottom: 20px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-title {\n");
      out.write("      font-size: 2em;\n");
      out.write("      font-weight: bold;\n");
      out.write("      margin-bottom: 12px;\n");
      out.write("      color: #333;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-meta {\n");
      out.write("      display: flex;\n");
      out.write("      gap: 16px;\n");
      out.write("      color: #666;\n");
      out.write("      font-size: 0.9em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-meta span {\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-body {\n");
      out.write("      margin-bottom: 32px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-section {\n");
      out.write("      margin-bottom: 24px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-section-title {\n");
      out.write("      font-size: 1.2em;\n");
      out.write("      font-weight: bold;\n");
      out.write("      margin-bottom: 12px;\n");
      out.write("      color: #444;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-price {\n");
      out.write("      font-size: 2em;\n");
      out.write("      font-weight: bold;\n");
      out.write("      color: #FF6B35;\n");
      out.write("      margin-bottom: 16px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-description {\n");
      out.write("      line-height: 1.8;\n");
      out.write("      color: #555;\n");
      out.write("      white-space: pre-wrap;\n");
      out.write("      background: #f9f9f9;\n");
      out.write("      padding: 20px;\n");
      out.write("      border-radius: 8px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-categories {\n");
      out.write("      display: flex;\n");
      out.write("      gap: 8px;\n");
      out.write("      flex-wrap: wrap;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .category-badge {\n");
      out.write("      background: #FF6B35;\n");
      out.write("      color: white;\n");
      out.write("      padding: 6px 14px;\n");
      out.write("      border-radius: 20px;\n");
      out.write("      font-size: 0.9em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .back-button {\n");
      out.write("      display: inline-block;\n");
      out.write("      margin-bottom: 20px;\n");
      out.write("      color: #FF6B35;\n");
      out.write("      text-decoration: none;\n");
      out.write("      font-weight: 500;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .back-button:hover {\n");
      out.write("      text-decoration: underline;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .contact-section {\n");
      out.write("      background: #f0f8ff;\n");
      out.write("      padding: 20px;\n");
      out.write("      border-radius: 8px;\n");
      out.write("      margin-top: 32px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .contact-email {\n");
      out.write("      font-size: 1.1em;\n");
      out.write("      color: #333;\n");
      out.write("      font-weight: 500;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comments-section {\n");
      out.write("      margin-top: 48px;\n");
      out.write("      padding-top: 32px;\n");
      out.write("      border-top: 2px solid #f0f0f0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comments-title {\n");
      out.write("      font-size: 1.5em;\n");
      out.write("      font-weight: bold;\n");
      out.write("      margin-bottom: 24px;\n");
      out.write("      color: #333;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comment-form {\n");
      out.write("      background: #f9f9f9;\n");
      out.write("      padding: 20px;\n");
      out.write("      border-radius: 8px;\n");
      out.write("      margin-bottom: 32px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comment-textarea {\n");
      out.write("      width: 100%;\n");
      out.write("      min-height: 100px;\n");
      out.write("      padding: 12px;\n");
      out.write("      border: 2px solid #ddd;\n");
      out.write("      border-radius: 6px;\n");
      out.write("      font-size: 1em;\n");
      out.write("      resize: vertical;\n");
      out.write("      font-family: inherit;\n");
      out.write("      box-sizing: border-box;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comment-textarea:focus {\n");
      out.write("      outline: none;\n");
      out.write("      border-color: #FF6B35;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comment-submit {\n");
      out.write("      margin-top: 12px;\n");
      out.write("      padding: 10px 24px;\n");
      out.write("      background: #FF6B35;\n");
      out.write("      color: white;\n");
      out.write("      border: none;\n");
      out.write("      border-radius: 6px;\n");
      out.write("      font-size: 1em;\n");
      out.write("      font-weight: 600;\n");
      out.write("      cursor: pointer;\n");
      out.write("      transition: all 0.2s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comment-submit:hover {\n");
      out.write("      background: #e55a2a;\n");
      out.write("      transform: translateY(-1px);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comments-list {\n");
      out.write("      display: flex;\n");
      out.write("      flex-direction: column;\n");
      out.write("      gap: 16px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comment-item {\n");
      out.write("      background: white;\n");
      out.write("      padding: 16px;\n");
      out.write("      border-radius: 8px;\n");
      out.write("      border: 1px solid #e0e0e0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comment-item.author {\n");
      out.write("      background: #fff8f5;\n");
      out.write("      border: 2px solid #FF6B35;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comment-header {\n");
      out.write("      display: flex;\n");
      out.write("      justify-content: space-between;\n");
      out.write("      align-items: center;\n");
      out.write("      margin-bottom: 12px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comment-author {\n");
      out.write("      font-weight: 600;\n");
      out.write("      color: #333;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comment-author.is-seller {\n");
      out.write("      color: #FF6B35;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comment-author .seller-badge {\n");
      out.write("      background: #FF6B35;\n");
      out.write("      color: white;\n");
      out.write("      font-size: 0.75em;\n");
      out.write("      padding: 2px 8px;\n");
      out.write("      border-radius: 12px;\n");
      out.write("      margin-left: 8px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comment-date {\n");
      out.write("      color: #999;\n");
      out.write("      font-size: 0.9em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comment-content {\n");
      out.write("      color: #555;\n");
      out.write("      line-height: 1.6;\n");
      out.write("      white-space: pre-wrap;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .no-comments {\n");
      out.write("      text-align: center;\n");
      out.write("      color: #999;\n");
      out.write("      padding: 40px 20px;\n");
      out.write("      background: #f9f9f9;\n");
      out.write("      border-radius: 8px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comment-item.highlight {\n");
      out.write("      animation: highlightFade 2s ease-in-out;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @keyframes highlightFade {\n");
      out.write("      0% {\n");
      out.write("        background-color: #fff3cd;\n");
      out.write("        transform: scale(1.02);\n");
      out.write("      }\n");
      out.write("      100% {\n");
      out.write("        background-color: inherit;\n");
      out.write("        transform: scale(1);\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comment-item.author.highlight {\n");
      out.write("      animation: highlightFadeAuthor 2s ease-in-out;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @keyframes highlightFadeAuthor {\n");
      out.write("      0% {\n");
      out.write("        background-color: #ffe8d9;\n");
      out.write("        transform: scale(1.02);\n");
      out.write("      }\n");
      out.write("      100% {\n");
      out.write("        background-color: #fff8f5;\n");
      out.write("        transform: scale(1);\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comment-item.highlight {\n");
      out.write("      animation: highlightFade 2s ease-in-out;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @keyframes highlightFade {\n");
      out.write("      0% {\n");
      out.write("        background-color: #fff3cd;\n");
      out.write("        transform: scale(1.02);\n");
      out.write("      }\n");
      out.write("      100% {\n");
      out.write("        background-color: inherit;\n");
      out.write("        transform: scale(1);\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .comment-item.author.highlight {\n");
      out.write("      animation: highlightFadeAuthor 2s ease-in-out;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @keyframes highlightFadeAuthor {\n");
      out.write("      0% {\n");
      out.write("        background-color: #ffe8d9;\n");
      out.write("        transform: scale(1.02);\n");
      out.write("      }\n");
      out.write("      100% {\n");
      out.write("        background-color: #fff8f5;\n");
      out.write("        transform: scale(1);\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<header class=\"nav\">\n");
      out.write("  <a href=\"index.jsp\" class=\"brand\">소리집 <span class=\"sub\">sorizip</span></a>\n");
      out.write("  <nav>\n");
      out.write("    <a href=\"index.jsp#features\">서비스 소개</a>\n");
      out.write("    <a href=\"index.jsp#categories\">카테고리</a>\n");
      out.write("    <a href=\"search.jsp\">검색</a>\n");
      out.write("    <a href=\"new.jsp\" style=\"color: #FF6B35; font-weight: 600;\">+ 매물 등록</a>\n");
      out.write("  </nav>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<div class=\"post-detail\">\n");
      out.write("  <a href=\"search.jsp\" class=\"back-button\">← 목록으로 돌아가기</a>\n");
      out.write("\n");
      out.write("  <div class=\"post-header\">\n");
      out.write("    <h1 class=\"post-title\">");
      out.print(post.title);
      out.write("</h1>\n");
      out.write("    <div class=\"post-meta\">\n");
      out.write("      <span>📅 ");
      out.print(post.createdAt);
      out.write("</span>\n");
      out.write("      ");
      if (post.categories != null && !post.categories.isEmpty()) {
        out.write("\n");
        out.write("      <span>🎵 ");
        out.print(post.categories);
        out.write("</span>\n");
        out.write("      ");
      }
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div class=\"post-body\">\n");
      out.write("    <div class=\"post-section\">\n");
      out.write("      <div class=\"post-price\">");
      out.print(formatPrice(post.price));
      out.write("</div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      if (post.categories != null && !post.categories.isEmpty()) {
        out.write("\n");
        out.write("    <div class=\"post-section\">\n");
        out.write("      <div class=\"post-section-title\">카테고리</div>\n");
        out.write("      <div class=\"post-categories\">\n");
        out.write("        ");
        for (String cat : post.categories.split(", ")) {
          out.write("\n");
          out.write("        <span class=\"category-badge\">");
          out.print(cat);
          out.write("</span>\n");
          out.write("        ");
        }
        out.write("\n");
        out.write("      </div>\n");
        out.write("    </div>\n");
        out.write("    ");
      }
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"post-section\">\n");
      out.write("      <div class=\"post-section-title\">상세 설명</div>\n");
      out.write("      <div class=\"post-description\">");
      out.print(post.description != null ? post.description : "상세 설명이 없습니다.");
      out.write("</div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      if (post.authorEmail != null) {
        out.write("\n");
        out.write("    <div class=\"contact-section\">\n");
        out.write("      <div class=\"post-section-title\">판매자 정보</div>\n");
        out.write("      <div class=\"contact-email\">📧 ");
        out.print(post.authorEmail);
        out.write("</div>\n");
        out.write("    </div>\n");
        out.write("    ");
      }
      out.write("\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- 댓글 섹션 -->\n");
      out.write("  <div class=\"comments-section\">\n");
      out.write("    <h2 class=\"comments-title\">댓글 (");
      out.print(comments.size());
      out.write(")</h2>\n");
      out.write("\n");
      out.write("    <!-- 댓글 작성 폼 -->\n");
      out.write("    <div class=\"comment-form\">\n");
      out.write("      <form method=\"post\" action=\"show.jsp\">\n");
      out.write("        <input type=\"hidden\" name=\"id\" value=\"");
      out.print(postId);
      out.write("\" />\n");
      out.write("        <input type=\"hidden\" name=\"commentAction\" value=\"submit\" />\n");
      out.write("        <textarea\n");
      out.write("          name=\"content\"\n");
      out.write("          class=\"comment-textarea\"\n");
      out.write("          placeholder=\"댓글을 작성해주세요...\"\n");
      out.write("          required\n");
      out.write("        ></textarea>\n");
      out.write("        <button type=\"submit\" class=\"comment-submit\">댓글 작성</button>\n");
      out.write("      </form>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 댓글 리스트 -->\n");
      out.write("    ");
      if (comments.isEmpty()) {
        out.write("\n");
        out.write("    <div class=\"no-comments\">\n");
        out.write("      아직 댓글이 없습니다. 첫 댓글을 작성해보세요!\n");
        out.write("    </div>\n");
        out.write("    ");
      } else {
        out.write("\n");
        out.write("    <div class=\"comments-list\">\n");
        out.write("      ");
        for (Comment comment : comments) {
          boolean isAuthor = comment.userId == post.authorId;

          out.write("\n");
          out.write("      <div id=\"comment-");
          out.print(comment.id);
          out.write("\" class=\"comment-item ");
          out.print(isAuthor ? "author" : "");
          out.write("\">\n");
          out.write("        <div class=\"comment-header\">\n");
          out.write("          <div class=\"comment-author ");
          out.print(isAuthor ? "is-seller" : "");
          out.write("\">\n");
          out.write("            ");
          out.print(comment.userEmail);
          out.write("\n");
          out.write("            ");
          if (isAuthor) {
            out.write("\n");
            out.write("            <span class=\"seller-badge\">판매자</span>\n");
            out.write("            ");
          }
          out.write("\n");
          out.write("          </div>\n");
          out.write("          <div class=\"comment-date\">");
          out.print(comment.createdAt);
          out.write("</div>\n");
          out.write("        </div>\n");
          out.write("        <div class=\"comment-content\">");
          out.print(comment.content);
          out.write("</div>\n");
          out.write("      </div>\n");
          out.write("      ");
        }
        out.write("\n");
        out.write("    </div>\n");
        out.write("    ");
      }
      out.write("\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<footer class=\"footer\">\n");
      out.write("  <div>© ");
      out.print(java.time.Year.now());
      out.write(" sorizip</div>\n");
      out.write("  <div>문의: support@sorizip.example</div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  // 페이지 로드 시 URL 해시에 해당하는 댓글로 스크롤\n");
      out.write("  document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("    const hash = window.location.hash;\n");
      out.write("    if (hash && hash.startsWith('#comment-')) {\n");
      out.write("      const commentElement = document.querySelector(hash);\n");
      out.write("      if (commentElement) {\n");
      out.write("        // 부드럽게 스크롤\n");
      out.write("        setTimeout(function() {\n");
      out.write("          commentElement.scrollIntoView({ behavior: 'smooth', block: 'center' });\n");
      out.write("          // 하이라이트 효과 추가\n");
      out.write("          commentElement.classList.add('highlight');\n");
      out.write("        }, 100);\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("  });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  // 페이지 로드 시 URL 해시에 해당하는 댓글로 스크롤\n");
      out.write("  document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("    const hash = window.location.hash;\n");
      out.write("    if (hash && hash.startsWith('#comment-')) {\n");
      out.write("      const commentElement = document.querySelector(hash);\n");
      out.write("      if (commentElement) {\n");
      out.write("        // 부드럽게 스크롤\n");
      out.write("        setTimeout(function() {\n");
      out.write("          commentElement.scrollIntoView({ behavior: 'smooth', block: 'center' });\n");
      out.write("          // 하이라이트 효과 추가\n");
      out.write("          commentElement.classList.add('highlight');\n");
      out.write("        }, 100);\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("  });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)) {
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {
          }
        if (_jspx_page_context != null)
          _jspx_page_context.handlePageException(t);
        else
          throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
