/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2025-11-24 01:11:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.example.web.Db;
import java.sql.ResultSet;

public final class show_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


  // 가격을 만원 단위로 포맷팅하는 함수
  String formatPrice(int price) {
    double manwon = price / 10000.0;
    if (manwon == (int) manwon) {
      return (int) manwon + "만원";
    } else {
      return String.format("%.1f만원", manwon);
    }
  }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.example.web.Db");
    _jspx_imports_classes.add("java.sql.ResultSet");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

  request.setCharacterEncoding("UTF-8");

  String idParam = request.getParameter("id");
  if (idParam == null || idParam.isEmpty()) {
    response.sendRedirect("search.jsp");
    return;
  }

  int postId = Integer.parseInt(idParam);

  // DB에서 게시글 상세 정보 가져오기
  class PostDetail {
    final int id;
    final String title;
    final String description;
    final int price;
    final String authorEmail;
    final String categories;
    final String createdAt;

    PostDetail(int id, String title, String description, int price, String authorEmail, String categories, String createdAt) {
      this.id = id;
      this.title = title;
      this.description = description;
      this.price = price;
      this.authorEmail = authorEmail;
      this.categories = categories;
      this.createdAt = createdAt;
    }
  }

  PostDetail post = null;
  try {
    String sql =
      "SELECT sp.id, sp.title, sp.description, sp.price, u.email, " +
      "       GROUP_CONCAT(c.name SEPARATOR ', ') as categories, " +
      "       sp.created_at " +
      "FROM sell_post sp " +
      "LEFT JOIN user u ON sp.author_id = u.id " +
      "LEFT JOIN sell_post_category spc ON sp.id = spc.sell_post_id " +
      "LEFT JOIN category c ON spc.category_id = c.id " +
      "WHERE sp.id = ? " +
      "GROUP BY sp.id, sp.title, sp.description, sp.price, u.email, sp.created_at";

    post = Db.query(sql, (ResultSet rs) -> {
      if (rs.next()) {
        return new PostDetail(
          rs.getInt("id"),
          rs.getString("title"),
          rs.getString("description"),
          rs.getInt("price"),
          rs.getString("email"),
          rs.getString("categories"),
          rs.getString("created_at")
        );
      }
      return null;
    }, postId);
  } catch (Exception e) {
    e.printStackTrace();
  }

  if (post == null) {
    response.sendRedirect("search.jsp");
    return;
  }

      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("  <title>");
      out.print( post.title );
      out.write(" – 소리집 sorizip</title>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/search.css\" />\n");
      out.write("  <style>\n");
      out.write("    .post-detail {\n");
      out.write("      max-width: 900px;\n");
      out.write("      margin: 0 auto;\n");
      out.write("      padding: 40px 20px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-header {\n");
      out.write("      margin-bottom: 24px;\n");
      out.write("      border-bottom: 2px solid #f0f0f0;\n");
      out.write("      padding-bottom: 20px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-title {\n");
      out.write("      font-size: 2em;\n");
      out.write("      font-weight: bold;\n");
      out.write("      margin-bottom: 12px;\n");
      out.write("      color: #333;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-meta {\n");
      out.write("      display: flex;\n");
      out.write("      gap: 16px;\n");
      out.write("      color: #666;\n");
      out.write("      font-size: 0.9em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-meta span {\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-body {\n");
      out.write("      margin-bottom: 32px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-section {\n");
      out.write("      margin-bottom: 24px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-section-title {\n");
      out.write("      font-size: 1.2em;\n");
      out.write("      font-weight: bold;\n");
      out.write("      margin-bottom: 12px;\n");
      out.write("      color: #444;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-price {\n");
      out.write("      font-size: 2em;\n");
      out.write("      font-weight: bold;\n");
      out.write("      color: #FF6B35;\n");
      out.write("      margin-bottom: 16px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-description {\n");
      out.write("      line-height: 1.8;\n");
      out.write("      color: #555;\n");
      out.write("      white-space: pre-wrap;\n");
      out.write("      background: #f9f9f9;\n");
      out.write("      padding: 20px;\n");
      out.write("      border-radius: 8px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .post-categories {\n");
      out.write("      display: flex;\n");
      out.write("      gap: 8px;\n");
      out.write("      flex-wrap: wrap;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .category-badge {\n");
      out.write("      background: #FF6B35;\n");
      out.write("      color: white;\n");
      out.write("      padding: 6px 14px;\n");
      out.write("      border-radius: 20px;\n");
      out.write("      font-size: 0.9em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .back-button {\n");
      out.write("      display: inline-block;\n");
      out.write("      margin-bottom: 20px;\n");
      out.write("      color: #FF6B35;\n");
      out.write("      text-decoration: none;\n");
      out.write("      font-weight: 500;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .back-button:hover {\n");
      out.write("      text-decoration: underline;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .contact-section {\n");
      out.write("      background: #f0f8ff;\n");
      out.write("      padding: 20px;\n");
      out.write("      border-radius: 8px;\n");
      out.write("      margin-top: 32px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .contact-email {\n");
      out.write("      font-size: 1.1em;\n");
      out.write("      color: #333;\n");
      out.write("      font-weight: 500;\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<header class=\"nav\">\n");
      out.write("  <a href=\"index.jsp\" class=\"brand\">소리집 <span class=\"sub\">sorizip</span></a>\n");
      out.write("  <nav>\n");
      out.write("    <a href=\"index.jsp#features\">서비스 소개</a>\n");
      out.write("    <a href=\"index.jsp#categories\">카테고리</a>\n");
      out.write("    <a href=\"index.jsp#market\">추천 매물</a>\n");
      out.write("    <a href=\"search.jsp\">검색</a>\n");
      out.write("  </nav>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<div class=\"post-detail\">\n");
      out.write("  <a href=\"javascript:history.back()\" class=\"back-button\">← 목록으로 돌아가기</a>\n");
      out.write("\n");
      out.write("  <div class=\"post-header\">\n");
      out.write("    <h1 class=\"post-title\">");
      out.print( post.title );
      out.write("</h1>\n");
      out.write("    <div class=\"post-meta\">\n");
      out.write("      <span>📅 ");
      out.print( post.createdAt );
      out.write("</span>\n");
      out.write("      ");
 if (post.categories != null && !post.categories.isEmpty()) { 
      out.write("\n");
      out.write("      <span>🎵 ");
      out.print( post.categories );
      out.write("</span>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div class=\"post-body\">\n");
      out.write("    <div class=\"post-section\">\n");
      out.write("      <div class=\"post-price\">");
      out.print( formatPrice(post.price) );
      out.write("</div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
 if (post.categories != null && !post.categories.isEmpty()) { 
      out.write("\n");
      out.write("    <div class=\"post-section\">\n");
      out.write("      <div class=\"post-section-title\">카테고리</div>\n");
      out.write("      <div class=\"post-categories\">\n");
      out.write("        ");
 for (String cat : post.categories.split(", ")) { 
      out.write("\n");
      out.write("        <span class=\"category-badge\">");
      out.print( cat );
      out.write("</span>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"post-section\">\n");
      out.write("      <div class=\"post-section-title\">상세 설명</div>\n");
      out.write("      <div class=\"post-description\">");
      out.print( post.description != null ? post.description : "상세 설명이 없습니다." );
      out.write("</div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
 if (post.authorEmail != null) { 
      out.write("\n");
      out.write("    <div class=\"contact-section\">\n");
      out.write("      <div class=\"post-section-title\">판매자 정보</div>\n");
      out.write("      <div class=\"contact-email\">📧 ");
      out.print( post.authorEmail );
      out.write("</div>\n");
      out.write("    </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<footer class=\"footer\">\n");
      out.write("  <div>© ");
      out.print( java.time.Year.now() );
      out.write(" sorizip</div>\n");
      out.write("  <div>문의: support@sorizip.example</div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
