db.driver=com.mysql.cj.jdbc.Driver
# ?? ????? ?? (Db.java?? System.getenv? ??)
# ?? ??? ?? ? ??? ???
db.jdbcUrl=jdbc:mysql://127.0.0.1:3310/sorizip?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
db.username=root
db.password=V%MsJN&Dh3@p4
# ?? ? ???
hikari.maximumPoolSize=10
hikari.connectionTimeoutMs=30000

# GCP Cloud Storage Configuration
GCP_PROJECT_ID=savvy-hybrid-479012-s9
GCS_BUCKET_NAME=sorizip-images
